CREATE DATABASE [Lab3-2_malikjp] 
CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'Lab3-2_malikjp', FILENAME = N'E:\Database\MSSQL12.MSSQLSERVER\MSSQL\DATA\Lab3-2_malikjp.mdf', SIZE = 6MB , MAXSIZE = 30MB, FILEGROWTH = 12% )
 LOG ON
( NAME = N'Lab3-2_malikjp_log', FILENAME = N'E:\Database\MSSQL12.MSSQLSERVER\MSSQL\DATA\Lab3-2_malikjp_log.mdf', SIZE = 3MB , MAXSIZE = 22MB , FILEGROWTH = 17%)
GO